### ISSUE TITLE
iOS7 MAC Address deprecated?

### ISSUE THREAD

**Issue by mramagem** [mohamed-salah/MacAddress#3]
Have you gotten this working on iOS7?

I'm reading everywhere that the ability to retrieve the Mac Address has been deprecated. So now, all we get back is a "02:00:00:00:00:00" dummy value.

I realize Apple wants developers to use other sorts of identifiers to track users, however, my current needs require an actual MAC Address since the app focuses on matching some network  connection info on WiFi.

Just wondering if you have been able to retrieve the MAC Address on iOS7 device? If so, can you share if you've made any tweaks? I'm on cordova 3.2

P.S. The plugin is working great on Android devices.

**Comment by yumincode** [comment]
hello,can anyone get the macAddress after iOS7?Please tell me ,thanks a lot...

**Comment by jcesarmobile** [comment]
No, it's not possible to get the macAddress after iOS 7
